const EXPLOSION_TYPE_TOP = 1;
const EXPLOSION_TYPE_LEFT = 2;
const EXPLOSION_TYPE_RIGHT = 3;
const EXPLOSION_TYPE_BOTTOM = 4;
const EXPLOSION_TYPE_CENTER = 5;

const TILE_TYPE_GRASS = 1;
const TILE_TYPE_OBSTACLE_BUSH = 2;
const TILE_TYPE_OBSTACLE_BALL = 3;
const TILE_TYPE_OBSTACLE_BOX = 9;
const TILE_TYPE_DIRT = 4;
const TILE_TYPE_TREE_TOP_LEFT = 5;
const TILE_TYPE_TREE_TOP_RIGHT = 6;
const TILE_TYPE_TREE_BOTTOM_LEFT = 7;
const TILE_TYPE_TREE_BOTTOM_RIGHT = 8;
const TILE_TYPE_BOOST_BOMB = 12;

const FIGURE_DIRECTION_TOP = 1;
const FIGURE_DIRECTION_BOTTOM = 2;
const FIGURE_DIRECTION_RIGHT = 3;
const FIGURE_DIRECTION_LEFT = 4;

const BOOST_TYPE_BOMB = 1;

if(typeof module !== 'undefined' && module.exports) {
  module.exports = {
    EXPLOSION_TYPE_TOP,
    EXPLOSION_TYPE_LEFT,
    EXPLOSION_TYPE_RIGHT,
    EXPLOSION_TYPE_BOTTOM,
    EXPLOSION_TYPE_CENTER,

    TILE_TYPE_GRASS,
    TILE_TYPE_OBSTACLE_BUSH,
    TILE_TYPE_OBSTACLE_BALL,
    TILE_TYPE_OBSTACLE_BOX,
    TILE_TYPE_DIRT,
    TILE_TYPE_TREE_TOP_LEFT,
    TILE_TYPE_TREE_TOP_RIGHT,
    TILE_TYPE_TREE_BOTTOM_LEFT,
    TILE_TYPE_TREE_BOTTOM_RIGHT,
    TILE_TYPE_BOOST_BOMB,

    FIGURE_DIRECTION_TOP,
    FIGURE_DIRECTION_BOTTOM,
    FIGURE_DIRECTION_RIGHT,
    FIGURE_DIRECTION_LEFT,

    BOOST_TYPE_BOMB,
  }
}